server:
  port: 8088
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
    min-response-size: 1024
spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB